/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OsTokenRouteImport } from './routes/os.$token'
import { Route as FaturaTokenRouteImport } from './routes/fatura.$token'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedOrdensRouteImport } from './routes/_authenticated/ordens'
import { Route as AuthenticatedFaturasRouteImport } from './routes/_authenticated/faturas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedOrdensIndexRouteImport } from './routes/_authenticated/ordens.index'
import { Route as AuthenticatedOrdensIdRouteImport } from './routes/_authenticated/ordens.$id'
import { Route as AuthenticatedFaturasIdRouteImport } from './routes/_authenticated/faturas.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OsTokenRoute = OsTokenRouteImport.update({
  id: '/os/$token',
  path: '/os/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturaTokenRoute = FaturaTokenRouteImport.update({
  id: '/fatura/$token',
  path: '/fatura/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdensRoute = AuthenticatedOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturasRoute = AuthenticatedFaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdensIndexRoute =
  AuthenticatedOrdensIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrdensRoute,
  } as any)
const AuthenticatedOrdensIdRoute = AuthenticatedOrdensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdensRoute,
} as any)
const AuthenticatedFaturasIdRoute = AuthenticatedFaturasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFaturasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faturas': typeof AuthenticatedFaturasRouteWithChildren
  '/ordens': typeof AuthenticatedOrdensRouteWithChildren
  '/produtos': typeof AuthenticatedProdutosRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/fatura/$token': typeof FaturaTokenRoute
  '/os/$token': typeof OsTokenRoute
  '/faturas/$id': typeof AuthenticatedFaturasIdRoute
  '/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/ordens/': typeof AuthenticatedOrdensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faturas': typeof AuthenticatedFaturasRouteWithChildren
  '/produtos': typeof AuthenticatedProdutosRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/fatura/$token': typeof FaturaTokenRoute
  '/os/$token': typeof OsTokenRoute
  '/faturas/$id': typeof AuthenticatedFaturasIdRoute
  '/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/ordens': typeof AuthenticatedOrdensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/faturas': typeof AuthenticatedFaturasRouteWithChildren
  '/_authenticated/ordens': typeof AuthenticatedOrdensRouteWithChildren
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/fatura/$token': typeof FaturaTokenRoute
  '/os/$token': typeof OsTokenRoute
  '/_authenticated/faturas/$id': typeof AuthenticatedFaturasIdRoute
  '/_authenticated/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/_authenticated/ordens/': typeof AuthenticatedOrdensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/faturas'
    | '/ordens'
    | '/produtos'
    | '/setup'
    | '/fatura/$token'
    | '/os/$token'
    | '/faturas/$id'
    | '/ordens/$id'
    | '/ordens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/faturas'
    | '/produtos'
    | '/setup'
    | '/fatura/$token'
    | '/os/$token'
    | '/faturas/$id'
    | '/ordens/$id'
    | '/ordens'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/faturas'
    | '/_authenticated/ordens'
    | '/_authenticated/produtos'
    | '/_authenticated/setup'
    | '/fatura/$token'
    | '/os/$token'
    | '/_authenticated/faturas/$id'
    | '/_authenticated/ordens/$id'
    | '/_authenticated/ordens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FaturaTokenRoute: typeof FaturaTokenRoute
  OsTokenRoute: typeof OsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/$token': {
      id: '/os/$token'
      path: '/os/$token'
      fullPath: '/os/$token'
      preLoaderRoute: typeof OsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fatura/$token': {
      id: '/fatura/$token'
      path: '/fatura/$token'
      fullPath: '/fatura/$token'
      preLoaderRoute: typeof FaturaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens': {
      id: '/_authenticated/ordens'
      path: '/ordens'
      fullPath: '/ordens'
      preLoaderRoute: typeof AuthenticatedOrdensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturas': {
      id: '/_authenticated/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof AuthenticatedFaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens/': {
      id: '/_authenticated/ordens/'
      path: '/'
      fullPath: '/ordens/'
      preLoaderRoute: typeof AuthenticatedOrdensIndexRouteImport
      parentRoute: typeof AuthenticatedOrdensRoute
    }
    '/_authenticated/ordens/$id': {
      id: '/_authenticated/ordens/$id'
      path: '/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AuthenticatedOrdensIdRouteImport
      parentRoute: typeof AuthenticatedOrdensRoute
    }
    '/_authenticated/faturas/$id': {
      id: '/_authenticated/faturas/$id'
      path: '/$id'
      fullPath: '/faturas/$id'
      preLoaderRoute: typeof AuthenticatedFaturasIdRouteImport
      parentRoute: typeof AuthenticatedFaturasRoute
    }
  }
}

interface AuthenticatedFaturasRouteChildren {
  AuthenticatedFaturasIdRoute: typeof AuthenticatedFaturasIdRoute
}

const AuthenticatedFaturasRouteChildren: AuthenticatedFaturasRouteChildren = {
  AuthenticatedFaturasIdRoute: AuthenticatedFaturasIdRoute,
}

const AuthenticatedFaturasRouteWithChildren =
  AuthenticatedFaturasRoute._addFileChildren(AuthenticatedFaturasRouteChildren)

interface AuthenticatedOrdensRouteChildren {
  AuthenticatedOrdensIdRoute: typeof AuthenticatedOrdensIdRoute
  AuthenticatedOrdensIndexRoute: typeof AuthenticatedOrdensIndexRoute
}

const AuthenticatedOrdensRouteChildren: AuthenticatedOrdensRouteChildren = {
  AuthenticatedOrdensIdRoute: AuthenticatedOrdensIdRoute,
  AuthenticatedOrdensIndexRoute: AuthenticatedOrdensIndexRoute,
}

const AuthenticatedOrdensRouteWithChildren =
  AuthenticatedOrdensRoute._addFileChildren(AuthenticatedOrdensRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaturasRoute: typeof AuthenticatedFaturasRouteWithChildren
  AuthenticatedOrdensRoute: typeof AuthenticatedOrdensRouteWithChildren
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaturasRoute: AuthenticatedFaturasRouteWithChildren,
  AuthenticatedOrdensRoute: AuthenticatedOrdensRouteWithChildren,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FaturaTokenRoute: FaturaTokenRoute,
  OsTokenRoute: OsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
